[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.fuzz]
seed = "0x0000000000000000000000000000000000000000000000000000000000000001"

[profile.default.invariant]
runs = 1
depth = 1

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
